version: '3.8'

services:
  pokedex:
    build: ./
    command: yarn dev
    container_name: poke
    ports:
      - 3000:3000
    volumes:
      - node_modules:/usr/app/node_modules
      - .:/usr/app

volumes:
  node_modules: {}
